---
- hosts: all
 
  tasks:

  - name: Update APT package cache
    apt: update=dist
     register: apt_result


  - name: Upgrade APT to the latest packages
    apt: upgrade=dist
    register: apt_result
